//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shantanel_Wpf_Kval_EgorPopelyuk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Discription { get; set; }
        public byte[] Images { get; set; }
        public Nullable<int> ID_prod { get; set; }
    
        public virtual Type_product Type_product { get; set; }
    }
}
